language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
- python setup.py -q install
# command to run tests
script:
- python -m unittest discover -v -s yandex_speech/tests
